-- MySQL Script generated by MySQL Workbench
-- Thu May 14 10:31:05 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistematmbndcimc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistematmbndcimc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistematmbndcimc` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `sistematmbndcimc` ;

-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`_prisma_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`_prisma_migrations` (
  `id` VARCHAR(36) NOT NULL,
  `checksum` VARCHAR(64) NOT NULL,
  `finished_at` DATETIME(3) NULL DEFAULT NULL,
  `migration_name` VARCHAR(255) NOT NULL,
  `logs` TEXT NULL DEFAULT NULL,
  `rolled_back_at` DATETIME(3) NULL DEFAULT NULL,
  `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `applied_steps_count` INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT '1',
  `email_verificado` TINYINT(1) NOT NULL DEFAULT '0',
  `ultimo_login` TIMESTAMP NULL DEFAULT NULL,
  `criado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuarios_email_key` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`dados_corporais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`dados_corporais` (
  `idDados` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `peso_kg` DECIMAL(10,2) NOT NULL,
  `altura_cm` DECIMAL(4,2) NOT NULL,
  `genero` ENUM('Masculino', 'Feminino', 'Outro') NOT NULL,
  `idade` INT NOT NULL,
  `nivel_atividade` ENUM('Sedentario', 'Leve', 'Moderado', 'Intenso', 'MuitoIntenso') NOT NULL,
  `data_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idDados`),
  UNIQUE INDEX `dados_corporais_idUsuario_key` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `dados_corporais_idUsuario_fkey`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sistematmbndcimc`.`usuarios` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`calculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`calculos` (
  `idCalculo` INT NOT NULL AUTO_INCREMENT,
  `idDados` INT NOT NULL,
  `imc` DECIMAL(10,2) NOT NULL,
  `tmb` DECIMAL(10,2) NOT NULL,
  `ndc` DECIMAL(10,2) NOT NULL,
  `data_calculo` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCalculo`),
  INDEX `calculos_idDados_fkey` (`idDados` ASC) VISIBLE,
  CONSTRAINT `calculos_idDados_fkey`
    FOREIGN KEY (`idDados`)
    REFERENCES `sistematmbndcimc`.`dados_corporais` (`idDados`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`email_verification_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`email_verification_tokens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(512) NOT NULL,
  `usuarioId` INT NOT NULL,
  `expira_em` DATETIME(3) NOT NULL,
  `criado_em` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_verification_tokens_token_key` (`token` ASC) VISIBLE,
  INDEX `email_verification_tokens_usuarioId_fkey` (`usuarioId` ASC) VISIBLE,
  CONSTRAINT `email_verification_tokens_usuarioId_fkey`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `sistematmbndcimc`.`usuarios` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`exercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`exercicios` (
  `idExercicio` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `caminho_video` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idExercicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`treinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`treinos` (
  `idTreino` INT NOT NULL AUTO_INCREMENT,
  `idCalculo` INT NOT NULL,
  `objetivo` ENUM('Hipertrofia', 'Emagrecimento', 'Resistencia', 'Condicionamento') NOT NULL,
  `nivel` ENUM('Iniciante', 'Intermediario', 'Avancado') NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idTreino`),
  INDEX `treinos_idCalculo_fkey` (`idCalculo` ASC) VISIBLE,
  CONSTRAINT `treinos_idCalculo_fkey`
    FOREIGN KEY (`idCalculo`)
    REFERENCES `sistematmbndcimc`.`calculos` (`idCalculo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`treinos_exercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`treinos_exercicios` (
  `idTreino` INT NOT NULL,
  `idExercicio` INT NOT NULL,
  `series` INT NOT NULL,
  `descanso_segundos` INT NOT NULL,
  `repeticoes` INT NOT NULL,
  `grupo_muscular` VARCHAR(250) NOT NULL,
  `tipo` ENUM('Forca', 'Cardio', 'Alongamento', 'Mobilidade') NOT NULL,
  PRIMARY KEY (`idTreino`, `idExercicio`),
  INDEX `treinos_exercicios_idExercicio_fkey` (`idExercicio` ASC) VISIBLE,
  CONSTRAINT `treinos_exercicios_idExercicio_fkey`
    FOREIGN KEY (`idExercicio`)
    REFERENCES `sistematmbndcimc`.`exercicios` (`idExercicio`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `treinos_exercicios_idTreino_fkey`
    FOREIGN KEY (`idTreino`)
    REFERENCES `sistematmbndcimc`.`treinos` (`idTreino`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `sistematmbndcimc`.`usuarios_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistematmbndcimc`.`usuarios_perfil` (
  `idUsuario` INT NOT NULL,
  `idPerfil` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `idPerfil`),
  INDEX `usuarios_perfil_idPerfil_fkey` (`idPerfil` ASC) VISIBLE,
  CONSTRAINT `usuarios_perfil_idPerfil_fkey`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `sistematmbndcimc`.`perfil` (`idPerfil`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `usuarios_perfil_idUsuario_fkey`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sistematmbndcimc`.`usuarios` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
